server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA — React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets com hash (Vite)
    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # Sem cache no index.html (novos deploys)
    location = /index.html {
        expires -1;
        add_header Cache-Control "no-store";
    }
}
