@baseUrl = http://localhost:3333
@empresaId = 1030c59f-503a-4dfc-ad8b-66c802060cd0
@token = {{login.response.body.token}}
@contratoId = {{listarContratos.response.body.data[0].id}}
@pagamentoId = {{listarPagamentos.response.body.data[0].id}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@empresademo.com.br",
  "senha": "admin123",
  "empresaId": "{{empresaId}}"
}

### Listar contratos
# @name listarContratos
GET {{baseUrl}}/contratos?limit=5
Authorization: Bearer {{token}}

### Listar pagamentos
# @name listarPagamentos
GET {{baseUrl}}/pagamentos?limit=5
Authorization: Bearer {{token}}

### Baixar recibo de pagamento (PDF)
GET {{baseUrl}}/pdf/recibo/{{pagamentoId}}
Authorization: Bearer {{token}}

### Baixar extrato do contrato (PDF)
GET {{baseUrl}}/pdf/extrato/{{contratoId}}
Authorization: Bearer {{token}}
